/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssociadosRouteImport } from './routes/associados'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAssociadosRouteImport } from './routes/admin.associados'
import { Route as AdminDefinicoesRouteImport } from './routes/admin.definicoes'
import { Route as AdminFicheirosRouteImport } from './routes/admin.ficheiros'
import { Route as AdminInstitucionalRouteImport } from './routes/admin.institucional'
import { Route as AdminMensagensRouteImport } from './routes/admin.mensagens'
import { Route as AdminNoticiasRouteImport } from './routes/admin.noticias'
import { Route as AdminOrgaosRouteImport } from './routes/admin.orgaos'
import { Route as AdminUtilizadoresRouteImport } from './routes/admin.utilizadores'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociadosRoute = AssociadosRouteImport.update({
  id: '/associados',
  path: '/associados',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssociadosRoute = AdminAssociadosRouteImport.update({
  id: '/associados',
  path: '/associados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDefinicoesRoute = AdminDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFicheirosRoute = AdminFicheirosRouteImport.update({
  id: '/ficheiros',
  path: '/ficheiros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstitucionalRoute = AdminInstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMensagensRoute = AdminMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticiasRoute = AdminNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgaosRoute = AdminOrgaosRouteImport.update({
  id: '/orgaos',
  path: '/orgaos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUtilizadoresRoute = AdminUtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => AdminRoute,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoticiasRoute,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoticiasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/associados': typeof AssociadosRoute
  '/contactos': typeof ContactosRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/associados': typeof AdminAssociadosRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/ficheiros': typeof AdminFicheirosRoute
  '/admin/institucional': typeof AdminInstitucionalRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/orgaos': typeof AdminOrgaosRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/associados': typeof AssociadosRoute
  '/contactos': typeof ContactosRoute
  '/sobre': typeof SobreRoute
  '/admin/associados': typeof AdminAssociadosRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/ficheiros': typeof AdminFicheirosRoute
  '/admin/institucional': typeof AdminInstitucionalRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/orgaos': typeof AdminOrgaosRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/admin': typeof AdminIndexRoute
  '/noticias': typeof NoticiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/associados': typeof AssociadosRoute
  '/contactos': typeof ContactosRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/admin/associados': typeof AdminAssociadosRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/ficheiros': typeof AdminFicheirosRoute
  '/admin/institucional': typeof AdminInstitucionalRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/orgaos': typeof AdminOrgaosRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/associados'
    | '/contactos'
    | '/noticias'
    | '/sobre'
    | '/admin/associados'
    | '/admin/definicoes'
    | '/admin/ficheiros'
    | '/admin/institucional'
    | '/admin/mensagens'
    | '/admin/noticias'
    | '/admin/orgaos'
    | '/admin/utilizadores'
    | '/noticias/$slug'
    | '/admin/'
    | '/noticias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/associados'
    | '/contactos'
    | '/sobre'
    | '/admin/associados'
    | '/admin/definicoes'
    | '/admin/ficheiros'
    | '/admin/institucional'
    | '/admin/mensagens'
    | '/admin/noticias'
    | '/admin/orgaos'
    | '/admin/utilizadores'
    | '/noticias/$slug'
    | '/admin'
    | '/noticias'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/associados'
    | '/contactos'
    | '/noticias'
    | '/sobre'
    | '/admin/associados'
    | '/admin/definicoes'
    | '/admin/ficheiros'
    | '/admin/institucional'
    | '/admin/mensagens'
    | '/admin/noticias'
    | '/admin/orgaos'
    | '/admin/utilizadores'
    | '/noticias/$slug'
    | '/admin/'
    | '/noticias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssociadosRoute: typeof AssociadosRoute
  ContactosRoute: typeof ContactosRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associados': {
      id: '/associados'
      path: '/associados'
      fullPath: '/associados'
      preLoaderRoute: typeof AssociadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/associados': {
      id: '/admin/associados'
      path: '/associados'
      fullPath: '/admin/associados'
      preLoaderRoute: typeof AdminAssociadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/definicoes': {
      id: '/admin/definicoes'
      path: '/definicoes'
      fullPath: '/admin/definicoes'
      preLoaderRoute: typeof AdminDefinicoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ficheiros': {
      id: '/admin/ficheiros'
      path: '/ficheiros'
      fullPath: '/admin/ficheiros'
      preLoaderRoute: typeof AdminFicheirosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/institucional': {
      id: '/admin/institucional'
      path: '/institucional'
      fullPath: '/admin/institucional'
      preLoaderRoute: typeof AdminInstitucionalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mensagens': {
      id: '/admin/mensagens'
      path: '/mensagens'
      fullPath: '/admin/mensagens'
      preLoaderRoute: typeof AdminMensagensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/noticias': {
      id: '/admin/noticias'
      path: '/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AdminNoticiasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orgaos': {
      id: '/admin/orgaos'
      path: '/orgaos'
      fullPath: '/admin/orgaos'
      preLoaderRoute: typeof AdminOrgaosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/utilizadores': {
      id: '/admin/utilizadores'
      path: '/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AdminUtilizadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof NoticiasRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAssociadosRoute: typeof AdminAssociadosRoute
  AdminDefinicoesRoute: typeof AdminDefinicoesRoute
  AdminFicheirosRoute: typeof AdminFicheirosRoute
  AdminInstitucionalRoute: typeof AdminInstitucionalRoute
  AdminMensagensRoute: typeof AdminMensagensRoute
  AdminNoticiasRoute: typeof AdminNoticiasRoute
  AdminOrgaosRoute: typeof AdminOrgaosRoute
  AdminUtilizadoresRoute: typeof AdminUtilizadoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssociadosRoute: AdminAssociadosRoute,
  AdminDefinicoesRoute: AdminDefinicoesRoute,
  AdminFicheirosRoute: AdminFicheirosRoute,
  AdminInstitucionalRoute: AdminInstitucionalRoute,
  AdminMensagensRoute: AdminMensagensRoute,
  AdminNoticiasRoute: AdminNoticiasRoute,
  AdminOrgaosRoute: AdminOrgaosRoute,
  AdminUtilizadoresRoute: AdminUtilizadoresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NoticiasRouteChildren {
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasSlugRoute: NoticiasSlugRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssociadosRoute: AssociadosRoute,
  ContactosRoute: ContactosRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
